[[constraint]]
  name = "github.com/gotestyourself/gotestyourself"
  version = "1.2.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.1.4"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "gopkg.in/src-d/go-git.v4"
  version = "4.0.0-rc5"
